# application.yml
spring:
  application:
    name: Blog # 애플리케이션 이름

  profiles:
    active: local # <--- 이 라인을 추가하거나 수정하세요!
    # 이렇게 설정하면 애플리케이션 시작 시 application-local.yml이 로드됩니다.

  # 여기에 모든 프로파일에 공통으로 적용될 설정을 넣을 수 있습니다.
  # 예를 들어, 로깅 설정이나 공통으로 사용하는 외부 API 키 등
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace