# application.yml

spring:
  application:
    name: Blog # ?????? ?? ??

  # H2 ?????? ??
  datasource:
    url: jdbc:h2:mem:blogdb;MODE=MySQL # ???? H2 ?????? (??: blogdb)
    # ???? H2 ?????? (???? ???? ???)? ????? ?? ??? ?? ??:
    # url: jdbc:h2:file:./data/blogdb;MODE=MySQL
    username: sa # H2 ?? ??? ??
    password: # H2 ?? ???? (????)
    driver-class-name: org.h2.Driver # H2 JDBC ???? ??? ??

  h2:
    console:
      enabled: true # H2 ??(? ?????) ???
      path: /h2-console # H2 ?? ?? ?? (?: http://localhost:8080/h2-console)
      settings:
        web-allow-others: true # ?? ?? ?? (?? ????? ?? ??!)

  jpa: # Java Persistence API (?????? ?? ORM ?? ?)
    hibernate:
      ddl-auto: update # JPA ???? ?? ?????? ??? ?? ??/???? (?? ? ??)
      # ?? ??: 'create', 'create-drop', 'none', 'validate'
    show-sql: true # ???? SQL ?? ?? ??
    properties:
      hibernate:
        format_sql: true # SQL ??? ?? ?? ???? ??